export const styles = {
  control: (styles: any) => ({
    ...styles,
    color: "#000",
    backgroundColor: "var(--primaryBG)",
    minWidth: "120px",
    padding: "0",
    fontSize: "14px",
    boxShadow: "none",
    marginBottom: "10px",
    minHeight: "30px",
    borderColor: "var(--lightTextColor) !important",
  }),
  option: (styles: any, { isFocused }) => ({
    ...styles,
    margin: "0",
    fontSize: "14px",
    padding: "2px 6px",
    height: "26px",
    borderBottom: "1px solid var(--secondaryBG)",
    backgroundColor: "var(--primaryBG)",
    color: isFocused ? "var(--mainTextColor)" : "var(--secondaryTextColor)",
    // width: "150px",
    overflow: "hidden !important",
  }),
  menuList: (provided: any) => ({
    ...provided,
    paddingTop: 0,
    paddingBottom: 0,
    border: "1px solid var(--lightTextColor)",
    overflow: "hidden",
    marginTop: "-5px",
    boxShadow: "2px 2px 10px rgba(0, 0, 0, 0.3)",
    borderRadius: "4px",
    backgroundColor: "var(--primaryBG)",
  }),
  singleValue: (provided: any) => ({
    ...provided,
    fontSize: "14px",
    color: "var(--mainTextColor)",
  }),
  dropdownIndicator: (provided: any) => ({ ...provided, padding: "0" }),
  indicatorSeparator: (provided: any) => ({
    ...provided,
    backgroundColor: "transparent",
  }),
};
